### PR TITLE
Make php-token-bucket a Composer package

### PR DESCRIPTION
**Pull request by davidrans**
- Updates tests to run on PHP 8, with the newest version of PHPUnit
- Sets up Psalm
- Sets up the newest version of PHPUnit
- Move tests and source files into their own directories
- Drop PHP 5 support
- Add Composer files
- style/psalm/bug-fixes
- Add README.md

cr_req 1

### CODE REVIEW

**Comment by davidrans** [comment]
image
QA :rocket:

**Comment by cdcline** [comment]
CR 👍

**Comment by cdcline** [comment]
CR 👍

**Comment by davidrans** [comment]
Tests are still passing
QA :rocket:

**Pull request merged**
